### ISSUE TITLE
Version updates required in Dockerfile

### ISSUE THREAD

**Issue by lancegliser** [digikin/fluentd-elastic-kibana#4]
Have a look at this issue: https://github.com/uken/fluent-plugin-elasticsearch/issues/789

The gems for `fluent-plugin-elasticsearch` and `elasticsearch-xpack` are out of date in the base image.
Fought for a long while trying to get those features documented in 5.x to work, this was much of the reason.

I'd suggest updating the Dockerfile to something like:

```dockerfile
FROM fluent/fluentd
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document"] # The current version is great
RUN ["gem", "install", "elasticsearch-xpack", "--version", "7.11.2"] # The image version is something like 5.x
# Copies a local elastic template file for use
# COPY ./conf/ecs-template.json /etc/fluentd/ecs-template.json
# Specifies a user with lesser privileges 
#USER fluent
```

**Comment by lancegliser** [comment]
Note that this was linked to from the [Fluentd website](https://docs.fluentd.org/container-deployment/docker-compose)

**Comment by digikin** [comment]
Sorry for missing this.  Want to do a pull request and ill test?

**Comment by digikin** [comment]
This is just a template. You can do whatever you want to it.
