### ISSUE TITLE
Filter fluentd logs issue

### ISSUE THREAD

**Issue by ssipos90** [digikin/fluentd-elastic-kibana#5]
Hi,

We're trying to set fluentd as the default docker driver using the example config using docker-compose (debian version for reasons explained at the bottom). I have installed elastic plugin (and systemd).
The problem is that fluentd logs itself and glitches with a bunch of \\\\, and I'm struggling to create a config that works.
I've tried using the FLUENT_LOG label, but logs keep showing in docker logs.

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
<label @FLUENT_LOG>
  <match fluent.*>
    @type stdout
  </match>
</label>
<match *.**>
  @type copy
  <store>
    @type elasticsearch
    host elasticsearch
    user elastic
    password *******
    port 9200
    logstash_format true
    logstash_prefix fluentd
    logstash_dateformat %Y%m%d
    include_tag_key true
    type_name access_log
    tag_key @log_name
    <buffer>
      flush_interval 1s
    </buffer>
  </store>
  <store>
    @type stdout
  </store>
</match>
```
A workaround would be to log this specific container to docker local driver, but I want fluentd to log itself.

As a side quest, I'm trying to mount `/var/log/journal`  to '/journal' and send to elastic the journal under a different index.

Any help would be appreciated.
Thanks!

**Comment by digikin** [comment]
Im not sure how to help you.  If you are using the docker-compose file the logging driver is set to "fluentd".
